# Site Settings
title: Standard Health Record
description: >
  An open source initiative to address the national problem of health data interoperability by creating a standard health record (SHR).


# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md

sass:
  sass_dir: _scss
  style: :compressed